"""Add bankName column to User

Revision ID: 59e14217337d
Revises: 
Create Date: 2023-08-05 18:12:28.383291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59e14217337d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bankName', sa.String(length=255), nullable=True))
        batch_op.alter_column('account',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=True)
        batch_op.alter_column('enairaId',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('enairaId',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('account',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('bankName')

    # ### end Alembic commands ###
